//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fonqentity.fonq_database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fonqEntities : DbContext
    {
        public fonqEntities()
            : base("name=fonqEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<distributie_product> distributie_product { get; set; }
        public virtual DbSet<prod_vest_voorraad> prod_vest_voorraad { get; set; }
        public virtual DbSet<vestiging> vestigings { get; set; }
    }
}
