//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fonqentity.fonq_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class prod_vest_voorraad
    {
        public int product_vest_id { get; set; }
        public Nullable<int> vestiging_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> voorraad_vest { get; set; }
    
        public virtual distributie_product distributie_product { get; set; }
        public virtual vestiging vestiging { get; set; }
    }
}
