//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fonqentity.fonq_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vestiging
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vestiging()
        {
            this.prod_vest_voorraad = new HashSet<prod_vest_voorraad>();
        }
    
        public int vestiging_id { get; set; }
        public string locatie { get; set; }
        public string naam { get; set; }
        public string telefoon { get; set; }
        public Nullable<int> personeel_aantal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prod_vest_voorraad> prod_vest_voorraad { get; set; }
    }
}
